### ISSUE TITLE
When there is only one input, "Scalar size does not match" error.

### ISSUE THREAD

**Issue by JofArnold** [iden3/snarkjs#116]
Appears to be a circom bug? Not sure exactly what the trigger is here but here's a couple of test cases

```
input.json 

{
  "a": 1
}
```

Ok:
```
pragma circom 2.0.0;

template Test() {
    signal input a;
    signal b;
}

component main = Test();
```

Fails:
```
pragma circom 2.0.0;

template Test() {
    signal input a;
}

component main = Test();
```

**Comment by hexLancel** [comment]
I had this same error, and I solved it by adding an output to the main component

**Comment by Divide-By-0** [comment]
I believe you need at least one public input or output!

**Comment by a2468834** [comment]
I got this error message, too.
And yes, it had been solved by add at least one public input or output to the main circuit.

**Comment by nihaoqingtuan** [comment]
i meet the same question,here is my code:

pragma circom 2.0.0;

template Multiplier2() {
    signal input a;
    signal input b;
    signal output c[100000];

    for(var i=0;i<100000;i++){
        c[i] <== a*b;
    }

}


 component main = Multiplier2();



who knows fix it?

**Comment by a2468834** [comment]
@nihaoqingtuan 

Could you please provide more details about what you were facing?
I have tried that piece of Circom code.
But, I passed all the procedures (compile + generate zkey + create full proof).

Here are codes I have tried:
```
// Circom code
pragma circom 2.0.0;

template Multiplier2() {
    signal input a;
    signal input b;
    signal output c[1000]; // Reduce the number for faster compiling
    
    for (var i = 0; i<1000; i++) {
        c[i] <== a*b;
    }

}

component main = Multiplier2();
```

```
// input.json
{
    "a": 2,
    "b": 3
}
```

**Comment by nihaoqingtuan** [comment]
@a2468834 

First of all, the circuit size I set is 18: 

> snarkjs powersoftau new bn128 18 pot12_0000.ptau -v


Then when I proceed to the following command, an error occurs：

`
$ snarkjs groth16 setup circuit.r1cs pot12_final.ptau circuit_0000.zkey
[INFO]  snarkJS: Reading r1cs
[INFO]  snarkJS: Reading tauG1
[INFO]  snarkJS: Reading tauG2
[INFO]  snarkJS: Reading alphatauG1
[INFO]  snarkJS: Reading betatauG1
[ERROR] snarkJS: Error: Scalar size does not match

`

**Comment by nihaoqingtuan** [comment]
@a2468834 

input.json:
{"a": "3", "b": "11"}

**Comment by nihaoqingtuan** [comment]
@a2468834 

I just reduced 100000 to 1000, and I can successfully pass the original wrong command. Is this because circom does not yet support such a large array range?

**Comment by a2468834** [comment]
Umh, so interesting.
When I compiled the circuit with `c[100000]`, I could reproduce that error message.

But I don't think it is because Circom isn't able to support # of constraints more than 100k. (I have written a Merkle tree circuit with ~2M  constraints.)

Those error messages are given from `snark.js` package. So I expect this is related to the implementation details about`snark.js`, or maybe you should use a smaller array in Circom circuits.

**Comment by a2468834** [comment]
Okay, I think I found the reason.
(Therefore, please ignore the previous reply.)

The number of `signal output` in your code is too large for `snark.js`. When I change the circuit into the following, I can pass all 3 procedures with `input.json` = `{"a": "3", "b": "11"}`.

```
// Circom
pragma circom 2.0.0;

template Multiplier2() {
    signal input a;
    signal input b;
    signal c[100000]; // Modify here
    
    for (var i = 0; i < 100000; i++) {
        c[i] <== a*b;
    }
}

component main{public [a, b]} = Multiplier2(); // Or you can add at least one `signal output`
```

**Comment by a2468834** [comment]
Besides, restricting the number of `signal input` and `output` is not wired. Instead, according to Table 1&2 in [Groth16](https://eprint.iacr.org/2016/260.pdf), Verifier's computation effort is related to the bit length of statements (i.e., how large `signal input` and `output` are), so keeping the set of `output` as small as possible would be a good choice.

If you write `signal output` for debugging, you can use `log()` [syntax](https://docs.circom.io/circom-language/code-quality/debugging-operations/) instead. Then, you can get the intermediate values during running `snarkjs groth16 fullprove`.

**Comment by nihaoqingtuan** [comment]
@a2468834 
感谢大佬！！！不得不说你对circom的了解挺深，我是在对几个不同的前端框架进行性能验证。我想问下题外话，除了文档还能从哪里了解更多关于circom+snarkjs的使用？因为我还想进行用https://github.com/privacy-scaling-explorations/perpetualpowersoftau来进行mpc可信设置。因为zokrates中文档说的的第一阶段就是用的这个powers of tau（但是我还没知道这个链接中下载下来的文件的使用方法）。

**Comment by lienhage** [comment]
Same issue;

my circuit: 

`pragma circom 2.0.0;

template Checker() {
    signal input a;
    signal input b;

    signal sum <== a + b;
    signal mul <== a * b;

    sum === 7;
    mul === 10;
}

component main{ public[a] } = Checker();`

input: 
{"a": 2, "b": 5}

**Comment by duongnd-183902** [comment]
I also encountered this error when testing the circuit without multiplication operation. However, it reminded me of the Snark algorithm based on Linear PCP used by Groth16, which uses the QAP (Quadratic Arithmetic Program) transcript instead of the representation like Plonk or Interactive Proof. 

My problem was solved when I added a multiplication constraint. Thank you if I made any mistakes.

**Comment by OBrezhniev** [comment]
@parizad1188 
> non-linear constraints: 0
> linear constraints: 2
> private inputs: 961200

You circuit logic is incorrect. You are not constraining your private inputs. You only have 2 linear constraints which are removed, because in groth16 they are not giving any security to the circuit. And in case of plonk you are proving only this 2 linear constraints.

See doc on circom simplifications:
https://docs.circom.io/circom-language/circom-insight/simplification/
