### ISSUE TITLE
bn128 pairing not computed correctly?

### ISSUE THREAD

**Issue by meilof** [iden3/snarkjs#31]
For a project of mine (https://github.com/meilof/pysnark) I am trying to convert Groth proofs generated by libsnark into a format that can be verified by snarkjs and by websnark (conversion script: https://github.com/meilof/pysnark/blob/master/pysnark/libsnark/tosnarkjsgg.py) .

The proofs are verified succesfully using websnark.

Unfortunately, the proofs fail to be verified by snarkjs. However, if in verifier_groth.js I use "bn128.pairing(vk_verifier.vk_alfa_1 , vk_verifier.vk_beta_2)" instead of vk_verifier.vk_alfabeta_12, the proofs check out. So apparently there is an inconsistency in how libsnark and snarkjs compute pairings (or represent the result).

I noticed that websnark does:

```
        const valid = this.instance.exports.bn128_pairingEq4(pA, pB, pIC, pGamma2, pC, pDelta2, pAlfa1, pBeta2, this.pOneT);
//        const valid = this.instance.exports.bn128_pairingEq3(pA, pB, pIC, pGamma2, pC, pDelta2, pAlfaBeta);
```

I also noticed that the proof generated using libsnark and converted using my conversion script work with both alternatives for the above verification, whereas proofs generated using snarkjs only work with the first one, i.e., they only work if the pairing pAlfaBeta computed by snarkjs is not used.

This seems to suggest to me that there is something wrong with the way pairings are computed in snarkjs. Maybe good to test its output against a reference output?

Hope this helps! Please let me know if you want to discuss this in more detail.

**Comment by yelhousni** [comment]
Indeed there is a slight difference between the pairing implementations in libsnark and snarkjs, but both are correct. In fact, the final exponentiation (FE) is computed differently and the result should be different because of an exponent cofactor. In the current implementation of snarkjs, the FE is `elt^((q^12-1)/r)` while in libsnark it is equal to `elt^(2z * ( 6z^2 + 3z + 1 )*(q^12-1)/r` where `z=4965661367192848881` is the seed of the alt-bn128 curve. You can always raise to a multiple of `(q^12-1)/r` that is not divisible by `r` and the pairing would be correct. The point to do so is to find a good LLL decomposition in `q^i`-basis and use Frobenius maps instead of modular exponentiations (see [[SAC:FueKnaRod11](https://pdfs.semanticscholar.org/4ec5/d70a5488e3a101b5d017ac8b29bfe2beb165.pdf)]).

I implemented this in this [PR]() and it should fix your problem.

**Comment by jbaylina** [comment]
In the new version we are using the wasmcurves lib that uses the right pairing.  Closing it.
