### ISSUE TITLE
the round1 in proof generation of plonk in snarkjs

### ISSUE THREAD

**Issue by VegeBun-csj** [iden3/snarkjs#402]
![image](https://github.com/iden3/snarkjs/assets/39252213/b0bf7c5d-f1c1-47f8-a154-54183dcf925e)
May I ask if there are any considerations for adding 4 commitments here? I have seen many plonk implementations of rust with 4 commitments

**Comment by VegeBun-csj** [comment]
@naps62 @jacobrosenthal @phated @uaoleg @phated @jbaylina hi guys, can we discuss it ?

**Comment by xavi-pinsach** [comment]
This code is useful to extend to 4*N evaluations because in the following rounds you more evaluations than N because of the degree of the polynomials you have to compute

**Comment by VegeBun-csj** [comment]
> This code is useful to extend to 4*N evaluations because in the following rounds you more evaluations than N because of the degree of the polynomials you have to compute

So, the community of snarkjs will have plan to apply the 4 commitments?

**Comment by xavi-pinsach** [comment]
For the computation of the polynomial t(X) of the plonk protocol we interpolate it from its evaluations. Due to the degree of the polynomial t(X) we need 4*N evaluations of it. To compute these evaluations we need evaluations of a(X), b(X) and c(X) and therefore we need 4*N evaluations of these polynomials
