### ISSUE TITLE
can't convert .circom file into json

### ISSUE THREAD

**Issue by yanzifan021** [iden3/snarkjs#47]
I want to convert my ``` circuit.circom ``` into a json file, so that i can parse it into circuitDef variable.
```const circuitDef = JSON.parse(fs.readFileSync("myCircuit.cir", "utf8"));```
I tried to use ```circom circuit.circom -o circuit.json``` to generate the json, nothing is generated after i run the command. 

the comment said ```"myCircuit.cir" is the output of the jaz compiler```, what does the jaz compiler mean?

**Comment by esortiz** [comment]
I think they have changed the library since last updating the readme. Now the circom library doesn't generate .json, but .r1cs. If you look in the tutorial you can see how circom works: https://github.com/iden3/circom/blob/master/TUTORIAL.md
It would be useful to update the readme. I see more or less how the library works now from the new tests, but I can't get it to work properly.
Thanks!

**Comment by jbaylina** [comment]
In the new version we include a an option to export the r1cs file to json

**Comment by Vishwas3000** [comment]
When i want to convert circuit.circom to json, I am unable to generate json file using ```circom circuit.circom -o circuit.json```. I was able to generate r1cs using ```circom circuit.circom --r1cs``` but how can i convert r1cs to json?
